name: Invalidate RSS and Home Page
on:
  push:
    paths:
      - sdelamocalendar.ics
      - posts/**
      - pages/**      
jobs:
  invalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Invalidate Feeds and Home Page    
        run: |
          aws cloudfront create-invalidation --distribution-id ECETJB04M75S7 --paths "/index.html /feed.json /rss.xml /blog/index.html"
